'use strict';
const $=s=>document.querySelector(s),video=$('#video'),canvas=$('#overlay'),ctx=canvas.getContext('2d');
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
const STORAGE='mamaai-health-log-v2',state=JSON.parse(localStorage.getItem(STORAGE)||'[]');
let stream=null,model=null,timer=null,busy=false,lastDrink=0,pending=null,recognizer=null;
const medicineWords=['аспирин','парацетамол','ибупрофен','нурофен','акмол','оптальгин','риталин','велбутрин','бупропион','ципралекс','сероквель','кветиапин','арипипразол','ламотриджин','мунжаро','mounjaro','vitamin','витамин','cardiloc','duplex'];

function setStatus(text){$('#status').textContent=text}
function speak(text){$('#assistantText').textContent=text;if(!('speechSynthesis'in window))return Promise.resolve();speechSynthesis.cancel();return new Promise(resolve=>{const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=.96;u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u)})}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));render()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function todayItems(){const d=new Date().toDateString();return state.filter(x=>new Date(x.at).toDateString()===d)}
function render(){const today=todayItems(),water=today.filter(x=>x.type==='water').reduce((n,x)=>n+(Number(x.amount)||0),0);$('#waterTotal').textContent=water;$('#medicineTotal').textContent=today.filter(x=>x.type==='medicine').length;$('#log').innerHTML=state.length?state.slice().reverse().map(x=>`<div class="entry"><span>${x.type==='water'?'💧':'💊'} <b>${esc(x.label)}</b></span><small>${new Date(x.at).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):'<p class="empty">Записей пока нет</p>'}

async function start(){if(!navigator.mediaDevices?.getUserMedia){return speak('Этот браузер не поддерживает камеру. Откройте программу в Google Chrome.')}try{setStatus('Запрашиваю камеру…');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();setStatus('Загружаю распознавание…');model=await cocoSsd.load({base:'lite_mobilenet_v2'});$('#cameraPlaceholder').hidden=true;$('#startBtn').disabled=true;$('#stopBtn').disabled=false;$('#medicineScanBtn').disabled=false;setStatus('Наблюдение активно');await speak('Камера включена. Я буду замечать воду и помогу записывать лекарства.');scan()}catch(e){console.error(e);setStatus('Нет доступа к камере');speak('Не удалось включить камеру. Разрешите доступ к камере в настройках Google Chrome.')}}
function stop(){clearTimeout(timer);recognizer?.abort();stream?.getTracks().forEach(t=>t.stop());stream=null;ctx.clearRect(0,0,canvas.width,canvas.height);$('#cameraPlaceholder').hidden=false;$('#startBtn').disabled=false;$('#stopBtn').disabled=true;$('#medicineScanBtn').disabled=true;setStatus('Наблюдение остановлено');$('#micDot').classList.remove('active');$('#micState').textContent='Микрофон ожидает диалога'}
async function scan(){if(!model||!stream)return;try{canvas.width=video.videoWidth;canvas.height=video.videoHeight;const items=await model.detect(video);ctx.clearRect(0,0,canvas.width,canvas.height);items.filter(x=>x.score>.55).forEach(draw);const drink=items.find(x=>['bottle','cup','wine glass'].includes(x.class)&&x.score>.64);if(drink&&!busy&&Date.now()-lastDrink>45000){lastDrink=Date.now();startDialog('water')}}catch(e){console.warn('scan',e)}finally{timer=setTimeout(scan,1300)}}
function draw(x){ctx.strokeStyle='#5cf2bf';ctx.lineWidth=4;ctx.strokeRect(...x.bbox);ctx.fillStyle='#5cf2bf';ctx.font='bold 18px system-ui';const names={bottle:'бутылка',cup:'стакан','wine glass':'бокал'};ctx.fillText(`${names[x.class]||x.class} ${Math.round(x.score*100)}%`,x.bbox[0],Math.max(22,x.bbox[1]-5))}

function listenOnce(timeout=9000){return new Promise(resolve=>{if(!Recognition)return resolve('');recognizer=new Recognition();recognizer.lang='ru-RU';recognizer.interimResults=false;recognizer.maxAlternatives=1;let done=false;const finish=v=>{if(done)return;done=true;$('#micDot').classList.remove('active');$('#micState').textContent='Микрофон ожидает диалога';resolve(v)};recognizer.onstart=()=>{$('#micDot').classList.add('active');$('#micState').textContent='Слушаю вас…'};recognizer.onresult=e=>finish(e.results[0][0].transcript.trim());recognizer.onerror=()=>finish('');recognizer.onend=()=>finish('');recognizer.start();setTimeout(()=>{try{recognizer.stop()}catch{}finish('')},timeout)})}
const isNo=t=>/\b(нет|не пил|не пила|не принимал|не принимала|ошибка|отмена)\b/i.test(t);
const isYes=t=>/\b(да|верно|правильно|выпил|выпила|принял|приняла|конечно)\b/i.test(t);
function numberFrom(t){const n=t.match(/\d+/);if(n)return Number(n[0]);const low=t.toLowerCase(),phrases={'двести пятьдесят':250,'сто пятьдесят':150,'триста пятьдесят':350,поллитра:500,сто:100,двести:200,триста:300,четыреста:400,пятьсот:500};for(const [w,value] of Object.entries(phrases))if(low.includes(w))return value;return null}

async function startDialog(type,suggested=''){if(busy)return;busy=true;pending={type,suggested};const water=type==='water';setupDialog(type,suggested);$('#dialog').showModal();await speak(water?'Молодец, вы пьёте воду. Вы действительно выпили воду? Скажите да или нет.':suggested?`Я вижу лекарство, возможно ${suggested}. Вы приняли его? Скажите да или нет.`:'Я вижу, вы принимаете лекарство? Скажите да или нет.');const answer=await listenOnce();if(isNo(answer)){cancelDialog();return}if(!isYes(answer)&&answer){$('#detailInput').value=water&&numberFrom(answer)||(!water?answer:'')}if(water){await speak('Сколько миллилитров воды вы выпили?');const amount=numberFrom(await listenOnce());if(amount)$('#detailInput').value=amount}else if(!suggested){await speak('Какое лекарство вы приняли?');const name=await listenOnce();if(name)$('#detailInput').value=name}else{$('#detailInput').value=suggested}if($('#detailInput').value){await speak(`Я услышала: ${water?$('#detailInput').value+' миллилитров':$('#detailInput').value}. Подтвердите кнопкой «Да, записать».`)}else await speak('Я не расслышала. Введите ответ в поле и подтвердите запись.')}
function setupDialog(type,suggested=''){const water=type==='water';$('#dialogIcon').textContent=water?'💧':'💊';$('#dialogTitle').textContent=water?'Вы выпили воду?':'Вы приняли лекарство?';$('#dialogText').textContent=water?'После подтверждения укажите объём.':'Проверьте название: камера может ошибаться.';$('#inputLabel').textContent=water?'Сколько миллилитров?':'Название лекарства';$('#detailInput').type=water?'number':'text';$('#detailInput').placeholder=water?'Например, 250':'Например, бупропион';$('#detailInput').value=suggested}
function cancelDialog(){if($('#dialog').open)$('#dialog').close('cancel')}

async function scanMedicine(){if(!stream||busy)return;busy=true;setStatus('Читаю упаковку…');await speak('Покажите упаковку лекарства ближе к камере. Я попробую прочитать название.');await new Promise(r=>setTimeout(r,1200));const snap=document.createElement('canvas');snap.width=video.videoWidth;snap.height=video.videoHeight;snap.getContext('2d').drawImage(video,0,0);try{const result=await Tesseract.recognize(snap,'rus+eng',{logger:m=>{if(m.status==='recognizing text')setStatus(`Читаю упаковку ${Math.round(m.progress*100)}%`)}});const raw=result.data.text.replace(/\s+/g,' ').trim(),low=raw.toLowerCase();const known=medicineWords.find(w=>low.includes(w));const guess=known||raw.split(' ').filter(w=>w.length>3).slice(0,3).join(' ');busy=false;setStatus('Наблюдение активно');startDialog('medicine',guess)}catch(e){console.error(e);busy=false;setStatus('Не удалось прочитать');startDialog('medicine','')}}

$('#dialog').addEventListener('close',()=>{recognizer?.abort();if($('#dialog').returnValue==='confirm'&&pending){const val=$('#detailInput').value.trim();if(!val){speak('Запись не сохранена: не указано количество или название.')}else if(pending.type==='water'&&(!(+val)||+val>5000)){speak('Проверьте количество. Запись не сохранена.')}else{state.push({type:pending.type,amount:pending.type==='water'?+val:null,label:pending.type==='water'?`${val} мл`:val,at:new Date().toISOString()});save();speak(pending.type==='water'?`Отлично. Записано ${val} миллилитров воды.`:`Записан приём лекарства: ${val}.`)}}else speak('Хорошо, я ничего не буду записывать.');busy=false;pending=null});
$('#startBtn').onclick=start;$('#stopBtn').onclick=stop;$('#medicineScanBtn').onclick=scanMedicine;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>startDialog(b.dataset.action));$('#clearBtn').onclick=()=>{if(confirm('Удалить весь журнал на этом устройстве?')){state.length=0;save()}};$('#exportBtn').onclick=()=>{const rows=['Дата,Тип,Значение',...state.map(x=>`${new Date(x.at).toLocaleString('ru-RU')},${x.type==='water'?'Вода':'Лекарство'},"${String(x.label).replaceAll('"','""')}"`)];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv'}));a.download='mamaai-health-journal.csv';a.click();URL.revokeObjectURL(a.href)};
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
