'use strict';
const $=s=>document.querySelector(s),video=$('#video'),canvas=$('#capture'),ctx=canvas.getContext('2d');
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
const LOG_KEY='mamaai-health-v2-log',SETTINGS_KEY='mamaai-health-v2-settings',KEY_STORE='mamaai-gemini-key';
let state=readJSON(LOG_KEY,[]),stream=null,timer=null,busy=false,dialogBusy=false,recognizer=null,facing='user',lastWater=0,lastMedicine=0;

function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function key(){return sessionStorage.getItem(KEY_STORE)||localStorage.getItem(KEY_STORE)||''}
function setAssistant(text){$('#assistantText').textContent=text}
function setStatus(text){setAssistant(text)}
function badge(id,on,text){const e=$(id);e.className='badge '+(on?'':'off');e.textContent=text}
function save(){localStorage.setItem(LOG_KEY,JSON.stringify(state));render()}
function addEvent(type,label,details={}){state.push({id:crypto.randomUUID?.()||String(Date.now()),type,label,details,at:new Date().toISOString()});save();setAssistant(type==='water'?`Записано: ${label} воды.`:`Записано лекарство: ${label}.`)}
function today(){const d=new Date().toDateString();return state.filter(x=>new Date(x.at).toDateString()===d)}
function render(){const t=today(),waters=t.filter(x=>x.type==='water'),total=waters.reduce((n,x)=>n+(Number(x.details.amount)||0),0);$('#waterTotal').textContent=total;$('#waterCount').textContent=waters.length;$('#medicineTotal').textContent=t.filter(x=>x.type==='medicine').length;$('#log').innerHTML=state.length?state.slice().reverse().map(x=>`<div class="entry"><span>${x.type==='water'?'💧':'💊'} <b>${esc(x.label)}</b></span><small>${new Date(x.at).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small><span class="meta">${esc(x.details.source||'Подтверждено голосом')}</span></div>`).join(''):'<p class="empty">Записей пока нет</p>'}

function loadSettings(){const s=readJSON(SETTINGS_KEY,{});['scanSeconds','cooldownSeconds','defaultWater','autoScan'].forEach(id=>{if(s[id]!==undefined){const e=$('#'+id);e.type==='checkbox'?e.checked=!!s[id]:e.value=s[id]}});const stored=localStorage.getItem(KEY_STORE)||'';if(stored){$('#apiKey').value=stored;$('#rememberKey').checked=true;$('#keyStatus').textContent='Google AI подключён в этом браузере.'}}
function saveSettings(){const s={};['scanSeconds','cooldownSeconds','defaultWater','autoScan'].forEach(id=>{const e=$('#'+id);s[id]=e.type==='checkbox'?e.checked:e.value});localStorage.setItem(SETTINGS_KEY,JSON.stringify(s))}
function connectKey(){const value=$('#apiKey').value.trim();if(!value){$('#keyStatus').textContent='Вставьте Gemini API key.';return}sessionStorage.setItem(KEY_STORE,value);if($('#rememberKey').checked)localStorage.setItem(KEY_STORE,value);else localStorage.removeItem(KEY_STORE);$('#keyStatus').textContent='Google AI подключён. Можно запускать камеру.';speak('Google AI подключён. Можно запускать помощника.')}

function speak(text){setAssistant(text);if(!('speechSynthesis'in window))return Promise.resolve();speechSynthesis.cancel();return new Promise(resolve=>{const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=.96;u.onend=resolve;u.onerror=resolve;speechSynthesis.speak(u)})}
function listen(timeout=9000,confirmMode=false){return new Promise(resolve=>{const yesBtn=$('#voiceYesBtn'),noBtn=$('#voiceNoBtn'),bar=$('#voiceConfirmBar');let done=false,to=null;const finish=v=>{if(done)return;done=true;clearTimeout(to);yesBtn.onclick=null;noBtn.onclick=null;bar.hidden=true;$('#micDot').classList.remove('active');$('#micState').textContent='Микрофон ожидает диалога';badge('#micBadge',false,'Микрофон');resolve((v||'').trim())};bar.hidden=!confirmMode;yesBtn.onclick=()=>finish('да');noBtn.onclick=()=>finish('нет');if(!Recognition){setAssistant(confirmMode?'Голос недоступен. Используйте кнопки «Да» или «Нет».':'Этот браузер не поддерживает распознавание речи. Откройте сайт в Google Chrome.');to=setTimeout(()=>finish(''),timeout);return}recognizer=new Recognition();recognizer.lang='ru-RU';recognizer.interimResults=false;recognizer.maxAlternatives=1;recognizer.onstart=()=>{$('#micDot').classList.add('active');$('#micState').textContent=confirmMode?'Слушаю «да» или «нет»…':'Слушаю вас…';badge('#micBadge',true,'Слушаю')};recognizer.onresult=e=>finish(e.results[0][0].transcript);recognizer.onerror=()=>{};recognizer.onend=()=>{if(!confirmMode)finish('')};to=setTimeout(()=>{try{recognizer.stop()}catch{}finish('')},timeout);setTimeout(()=>{try{recognizer.start()}catch{if(!confirmMode)finish('')}},450)})}
const isNo=t=>/\b(нет|неа|ошиблась|ошибся|не пил|не пила|не принимал|не принимала|отмена)\b/i.test(t||'');
const isYes=t=>/\b(да|ага|угу|верно|правильно|выпил|выпила|принял|приняла|конечно)\b/i.test(t||'');
function amountFrom(text=''){const low=text.toLowerCase().replace(',','.');const words={'сто':100,'сто пятьдесят':150,'двести':200,'двести пятьдесят':250,'триста':300,'триста пятьдесят':350,'четыреста':400,'пятьсот':500,'пол литра':500,'поллитра':500,'литр':1000};for(const [w,n] of Object.entries(words).sort((a,b)=>b[0].length-a[0].length))if(low.includes(w))return n;const m=low.match(/\d+(?:\.\d+)?/);if(!m)return null;let n=parseFloat(m[0]);if(low.includes('литр')&&n<10)n*=1000;return Math.round(n)}

async function start(){if(!key()){await speak('Сначала вставьте Gemini API key и нажмите подключить Google AI.');$('#apiKey').focus();return}if(!navigator.mediaDevices?.getUserMedia){return speak('Этот браузер не поддерживает камеру. Откройте сайт в Google Chrome.')}try{setStatus('Запрашиваю разрешение камеры…');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();$('#placeholder').hidden=true;$('#startBtn').disabled=true;$('#stopBtn').disabled=false;$('#scanBtn').disabled=false;$('#switchBtn').disabled=false;badge('#cameraBadge',true,'Камера включена');await speak('Помощник запущен. Я буду смотреть, что находится у вас в руках, и спрашивать подтверждение.');schedule(1200)}catch(e){console.error(e);badge('#cameraBadge',false,'Камера');speak('Не удалось включить камеру. Разрешите доступ к камере в настройках браузера.')}}
function stop(){clearTimeout(timer);recognizer?.abort();stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;$('#placeholder').hidden=false;$('#startBtn').disabled=false;$('#stopBtn').disabled=true;$('#scanBtn').disabled=true;$('#switchBtn').disabled=true;badge('#cameraBadge',false,'Камера');badge('#micBadge',false,'Микрофон');setStatus('Наблюдение остановлено.')}
function schedule(delay){clearTimeout(timer);if(!stream)return;timer=setTimeout(async()=>{if($('#autoScan').checked)await analyze();schedule(Math.max(5,Number($('#scanSeconds').value)||12)*1000)},delay)}
function capture(){const ratio=video.videoWidth/video.videoHeight||16/9,w=768;canvas.width=w;canvas.height=Math.round(w/ratio);ctx.drawImage(video,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.68)}
function flash(){const e=$('#scanFlash');e.classList.remove('active');void e.offsetWidth;e.classList.add('active')}

async function callGemini(image){const prompt=`Проанализируй один кадр с веб-камеры помощника здоровья. Особое внимание удели предметам В РУКАХ человека и предметам возле губ. Верни только JSON без markdown: {"scene":"краткое описание по-русски","objects_in_hands":["названия по-русски"],"water_related":false,"drinking_likely":false,"medicine_related":false,"medicine_name":null,"visible_text":"","confidence":0.0}. water_related=true, если в руках бутылка, стакан, чашка, кружка или похожая посуда. drinking_likely=true только если сосуд находится у губ или явно наклонён для питья. medicine_related=true для коробки лекарства, блистера, баночки таблеток, ингалятора, шприц-ручки или другой медицинской упаковки. Прочитай название лекарства с упаковки. Если не уверен — medicine_name=null. Не утверждай, что человек проглотил лекарство.`;const models=['gemini-2.5-flash','gemini-2.0-flash'];let lastError='';for(const model of models){const url=`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key())}`;const body={contents:[{parts:[{text:prompt},{inline_data:{mime_type:'image/jpeg',data:image.split(',')[1]}}]}],generationConfig:{temperature:.1,responseMimeType:'application/json'}};const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const raw=await r.json();if(!r.ok){lastError=raw?.error?.message||`Ошибка ${r.status}`;continue}const text=raw?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';const cleaned=text.replace(/^```json\s*/i,'').replace(/```$/,'').trim();try{return JSON.parse(cleaned)}catch{lastError='Google вернул непонятный ответ'}}throw new Error(lastError||'Google AI недоступен')}
async function analyze(){if(!stream||busy||dialogBusy||video.readyState<2)return;busy=true;flash();setStatus('Google AI анализирует предметы в руках…');try{const data=await callGemini(capture());$('#scene').textContent=data.scene||'Кадр проанализирован.';$('#confidence').textContent=`${Math.round((Number(data.confidence)||0)*100)}%`;$('#objects').innerHTML=(data.objects_in_hands||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('');setStatus(data.scene||'Анализ завершён.');await react(data)}catch(e){console.error(e);setStatus('Ошибка Google AI: '+e.message);if(/key|API|quota|permission/i.test(e.message))$('#keyStatus').textContent='Проверьте Gemini API key: '+e.message}finally{busy=false}}
async function react(data){const wait=Math.max(20,Number($('#cooldownSeconds').value)||75)*1000,now=Date.now();if(data.medicine_related&&now-lastMedicine>wait){lastMedicine=now;await medicineFlow(data);return}if((data.drinking_likely||data.water_related)&&now-lastWater>wait){lastWater=now;await waterFlow(data)}}

async function waterFlow(data={}){if(dialogBusy)return;dialogBusy=true;await speak(data.drinking_likely?'О, отлично, вы пьёте воду. Вы выпили воду? Скажите да или нет.':'Я вижу у вас стакан или бутылку. Вы выпили воду? Скажите да или нет.');const answer=await listen(9000,true);if(isNo(answer)){await speak('Отлично, я ничего не буду записывать.');dialogBusy=false;return}if(!isYes(answer)){await speak('Я не расслышала подтверждение, поэтому ничего не записываю.');dialogBusy=false;return}await speak('Сколько миллилитров?');let amount=amountFrom(await listen());if(!amount||amount<10||amount>5000){await speak('Я не смогла понять количество. Скажите ещё раз, сколько миллилитров.');amount=amountFrom(await listen())}if(!amount||amount<10||amount>5000){await speak('Количество не записано.');dialogBusy=false;return}await speak(`Я услышала ${amount} миллилитров. Записать? Скажите да или нет.`);const confirmation=await listen(9000,true);if(!isYes(confirmation)){await speak('Хорошо, воду не записываю.');dialogBusy=false;return}addEvent('water',`${amount} мл`,{amount,source:data.scene||'Голосовая запись'});await speak(`Хорошо. Я записала ${amount} миллилитров воды.`);dialogBusy=false}

async function medicineFlow(data={}){if(dialogBusy)return;dialogBusy=true;let name=(data.medicine_name||'').trim();if(name){await speak(`Похоже, у вас в руках лекарство ${name}. Вы действительно принимаете ${name}? Скажите да или нет.`);const answer=await listen(9000,true);if(isNo(answer)){await speak('Какое лекарство вы принимаете?');const corrected=await listen();if(!corrected){await speak('Я не расслышала название и ничего не записываю.');dialogBusy=false;return}name=corrected}else if(!isYes(answer)){await speak('Я не получила подтверждение и ничего не записываю.');dialogBusy=false;return}}else{await speak('А, вы принимаете лекарство? Какое лекарство вы принимаете?');name=await listen();if(!name){await speak('Я не расслышала название и ничего не записываю.');dialogBusy=false;return}}await speak(`Я услышала ${name}. Подтвердите: это правильное название?`);const confirm=await listen(9000,true);if(!isYes(confirm)){await speak('Хорошо, лекарство не записываю.');dialogBusy=false;return}await speak('Какую дозировку вы приняли?');const dose=await listen();addEvent('medicine',name,{dose:dose||'не указана',source:data.scene||'Голосовая запись',visibleText:data.visible_text||''});await speak(`Хорошо. Я записала лекарство ${name}${dose?`, дозировка ${dose}`:''}.`);dialogBusy=false}

$('#saveKeyBtn').onclick=connectKey;$('#startBtn').onclick=start;$('#stopBtn').onclick=stop;$('#scanBtn').onclick=analyze;$('#switchBtn').onclick=async()=>{facing=facing==='user'?'environment':'user';if(stream){stop();await start()}};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>b.dataset.action==='water'?waterFlow({scene:'Ручная голосовая запись'}):medicineFlow({scene:'Ручная голосовая запись'}));['scanSeconds','cooldownSeconds','defaultWater','autoScan'].forEach(id=>$('#'+id).addEventListener('change',saveSettings));$('#clearBtn').onclick=()=>{if(confirm('Удалить весь журнал здоровья в этом браузере?')){state=[];save()}};$('#exportBtn').onclick=()=>{const rows=['Дата,Тип,Значение,Дозировка',...state.map(x=>`${new Date(x.at).toLocaleString('ru-RU')},${x.type==='water'?'Вода':'Лекарство'},"${String(x.label).replaceAll('"','""')}","${String(x.details.dose||'').replaceAll('"','""')}"`)];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv'}));a.download='mamaai-health-journal.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));
loadSettings();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});