const $=s=>document.querySelector(s);const video=$('#video'),canvas=$('#overlay'),ctx=canvas.getContext('2d');let stream,model,timer,busy=false,lastSeen=0,pending=null;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;const state=JSON.parse(localStorage.getItem('healthVisionLog')||'[]');
function speak(text){$('#assistantText').textContent=text;if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}}
function save(){localStorage.setItem('healthVisionLog',JSON.stringify(state));render()}
function render(){const water=state.filter(x=>x.type==='water').reduce((n,x)=>n+(+x.amount||0),0),meds=state.filter(x=>x.type==='medicine').length;$('#waterTotal').textContent=water;$('#medicineTotal').textContent=meds;$('#log').innerHTML=state.length?state.slice().reverse().map(x=>`<div class="entry"><span>${x.type==='water'?'💧':'💊'} <b>${escapeHtml(x.label)}</b></span><small>${new Date(x.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):'<p class="empty">Записей пока нет</p>'}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function start(){try{$('#status').textContent='Загрузка модели…';stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});video.srcObject=stream;await video.play();model=await cocoSsd.load();$('#cameraPlaceholder').hidden=true;$('#startBtn').disabled=true;$('#stopBtn').disabled=false;$('#status').textContent='Наблюдение активно';speak('Камера включена. Я буду спрашивать подтверждение перед каждой записью.');scan()}catch(e){$('#status').textContent='Нет доступа к камере';speak('Не удалось включить камеру. Разрешите доступ в настройках браузера.') }}
function stop(){clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());ctx.clearRect(0,0,canvas.width,canvas.height);$('#cameraPlaceholder').hidden=false;$('#startBtn').disabled=false;$('#stopBtn').disabled=true;$('#status').textContent='Наблюдение остановлено'}
async function scan(){if(!model||!stream)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;const items=await model.detect(video);ctx.clearRect(0,0,canvas.width,canvas.height);items.filter(x=>x.score>.55).forEach(x=>{ctx.strokeStyle='#49e4b1';ctx.lineWidth=4;ctx.strokeRect(...x.bbox);ctx.fillStyle='#49e4b1';ctx.font='18px sans-serif';ctx.fillText(`${x.class} ${Math.round(x.score*100)}%`,x.bbox[0],Math.max(22,x.bbox[1]))});const drink=items.find(x=>['bottle','cup','wine glass'].includes(x.class)&&x.score>.62);if(drink&&!busy&&Date.now()-lastSeen>20000){lastSeen=Date.now();openConfirm('water')}timer=setTimeout(scan,1200)}
function listen(callback){if(!Recognition)return;const r=new Recognition();r.lang='ru-RU';r.interimResults=false;r.onresult=e=>callback(e.results[0][0].transcript);r.start()}
function openConfirm(type){busy=true;pending=type;const water=type==='water';$('#dialogIcon').textContent=water?'💧':'💊';$('#dialogTitle').textContent=water?'Вы выпили воду?':'Вы приняли лекарство?';$('#dialogText').textContent=water?'Камера заметила бутылку или стакан. Подтвердите запись.':'Укажите название лекарства и подтвердите приём.';$('#inputLabel').textContent=water?'Сколько миллилитров?':'Название лекарства';$('#detailInput').type=water?'number':'text';$('#detailInput').placeholder=water?'Например, 250':'Например, витамин D';$('#detailInput').value='';$('#confirmDialog').showModal();speak(water?'О, отлично, вы пьёте воду. Вы выпили воду?':'Вы принимаете лекарство? Какое лекарство вы принимаете?');setTimeout(()=>listen(text=>{const no=/\b(нет|ошибка|не пил|не принимал)\b/i.test(text);if(no){$('#confirmDialog').close('cancel')}else{const n=text.match(/\d+/);$('#detailInput').value=water&&n?n[0]:text}}),700)}
$('#confirmDialog').addEventListener('close',()=>{if($('#confirmDialog').returnValue==='confirm'){const val=$('#detailInput').value.trim();if(!val){speak('Запись не сохранена: не указано количество или название.')}else{state.push({type:pending,amount:pending==='water'?+val:null,label:pending==='water'?`${val} мл`:val,at:new Date().toISOString()});save();speak(pending==='water'?`Записано ${val} миллилитров воды.`:`Записан приём: ${val}.`)}}else speak('Хорошо, я ничего не буду записывать.');busy=false;pending=null});
$('#startBtn').onclick=start;$('#stopBtn').onclick=stop;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openConfirm(b.dataset.action));$('#clearBtn').onclick=()=>{if(confirm('Удалить весь журнал на этом устройстве?')){state.length=0;save()}};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
